# Generated by Django 5.1.2 on 2024-11-13 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 15, 41, 3, 906443, tzinfo=datetime.timezone.utc), editable=False, help_text='The timestamp when this session will expire\\.'),
        ),
    ]
