# Generated by Django 5.1.2 on 2024-11-14 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_session_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 14, 16, 7, 40, 195018, tzinfo=datetime.timezone.utc), editable=False, help_text='The timestamp when this session will expire\\.'),
        ),
    ]
