# Generated by Django 5.1.2 on 2025-01-17 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_alter_blockedip_options_alter_requestlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarytoken',
            name='path',
            field=models.CharField(default='updateServer', editable=False, help_text='Path of the request.', max_length=128, verbose_name='path'),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(help_text='The name of the server.', max_length=100, unique=True, verbose_name='Server Name'),
        ),
        migrations.AlterField(
            model_name='session',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 17, 12, 14, 48, 732932, tzinfo=datetime.timezone.utc), editable=False, help_text='The timestamp when this session will expire\\.', verbose_name='Session expiry'),
        ),
        migrations.AlterField(
            model_name='temporarytoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 17, 10, 16, 48, 733538, tzinfo=datetime.timezone.utc), editable=False, help_text='The timestamp when this token will expire\\.', verbose_name='Temporary Token expiry'),
        ),
    ]
