# Generated by Django 5.1.2 on 2025-02-03 11:37

import session.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_server_screens_alter_session_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expires',
            field=models.DateTimeField(default=session.models.get_expiry_time_session, editable=False, help_text='The timestamp when this session will expire\\.', verbose_name='Session expiry'),
        ),
        migrations.AlterField(
            model_name='temporarytoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp when this token was created.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='temporarytoken',
            name='expires_at',
            field=models.DateTimeField(default=session.models.get_expiry_time_token, editable=False, help_text='The timestamp when this token will expire.', verbose_name='Temporary Token expiry'),
        ),
    ]
